### PR TITLE
Fixed integration of FIRMessagingDelegate for iOS 10 devices

### PR DESCRIPTION
**Pull request by skulawik**
didRefreshRegistrationToken was missing, furthermore the class was not applying to the Protocol FIRMessagingDelegate.

### CODE REVIEW

**Comment by cooperka** [comment]
Is this change backwards-compatible with FCM SDK v3? I think this was caused by a breaking change in the FCM SDK v4, in which case we probably need a more detailed update to the README and release notes for this.

**Comment by skulawik** [comment]
As far as I have seen it it was the only breaking change for the new iOS SDK v4. 
However I recommend to refactor the iOS SDK anyway:

- it is currently not working as a cocoapod library
- separation of concerns, especially regarding interfacing between react and communication to firebase
- remove calls to deprecated functions for v4

I haven't tested my PR with v3; so this might be something we should test. I suggest to have a branch that complies to v3 and working in the upcoming develop branch with v4. At the moment there is only a master branch, this should be changed as well.

**Comment by evollu** [comment]
thanks for the PR
what is the different between onTokenRefresh() and didRefreshRegistrationToken()? can you provide link to documentation?
I've created iosv4 branch so you can PR against that.

**Comment by evollu** [comment]
done in v7

**Pull request closed without merging**
