### PR TITLE
feature(android): add support for badge count

### PR DESCRIPTION
**Pull request by sondremare**
Using Leolin's ShortcutBadger we are able to support any badge counts that are sent as part of the notifications data-payload.

### CODE REVIEW

**Comment by evollu** [comment]
great! any extra configuration needed?

**Comment by evollu** [comment]
can you fix the conflicts?

**Comment by sondremare** [comment]
Conflicts fixed.
It should not require any extra configuration. It will automatically respond to notifications that have badge in their data payload. Otherwise one can use the setBadgeNumber to manipulate the badge manually

**Comment by evollu** [comment]
will test and release

**Comment by sondremare** [comment]
cool thanks :)

**Comment by evollu** [comment]
@sondremare tried the function but no badge is showing up. Does it only work for specific system?

**Comment by sondremare** [comment]
Ah that should ofc been said. It works for specific vendors (LG, Samsung), as the code letting us draw this badge is part of the firmware. See https://github.com/leolin310148/ShortcutBadger

**Comment by malitta** [comment]
@sondremare the documentation still states that it doesn't support badges in Android. Should this be changed or hasn't this feature been officially released yet?

**Comment by sondremare** [comment]
@malitta I am just a contributor, so I am not sure. @evollu you have any information?

**Comment by evollu** [comment]
I will change the readme

**Comment by nhuthan** [comment]
(android) setBadgeNumber work but data-payload dont work
Here is my payload data:
`{
	collapse_key = "abc",
	data = new {
		badge = 10,
	},
	time_to_live = 864000, //10 days
	notification = new
	{
		id = "id",
		color = "#66BB6A",
		title = "the title",
		body = "the content",
		icon = "ic_notification",
		priority = "high",
		show_in_foreground = true,
		content_available = true,
		badge = 10,
		sound = "default",
	},
	registration_ids = [list id]
};`

What i am missing?

**Comment by sondremare** [comment]
Try structuring your payload like this:
```
{
    collapse_key: 'abc',
    data: {
        badge: 10,
        more_stuff: more_values,
    },
}
```

**Comment by evollu** [comment]
badge should be in `notification` payload

**Pull request merged**
