### PR TITLE
Add ProGuard information & improve README

### LINKED ISSUE #48: [android] not compatible with proguard
When I enable proguard, it does build but the app crashes right before starting.

```
:app:proguardRelease
Warning: com.google.android.gms.internal.zzw$zza: can't find superclass or interface org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzac: can't find referenced class android.net.http.AndroidHttpClient
Warning: com.google.android.gms.internal.zzac: can't find referenced class android.net.http.AndroidHttpClient
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.Header
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.Header
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpEntity
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.StatusLine
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.impl.cookie.DateUtils
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.impl.cookie.DateUtils
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.Header
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.Header
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpEntity
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpEntity
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpEntity
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.StatusLine
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.StatusLine
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.StatusLine
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.HttpEntity
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.Header
Warning: com.google.android.gms.internal.zzt: can't find referenced class org.apache.http.Header
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.HttpClient
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpDelete
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpGet
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpHead
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpOptions
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPost
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPut
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpTrace
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.entity.ByteArrayEntity
Warning: com.google.android.gms.internal.zzw: can't find referenced method 'void addHeader(java.lang.String,java.lang.String)' in program class com.google.android.gms.internal.zzw$zza
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpDelete
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpGet
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpHead
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpOptions
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPost
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPost
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPost
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPut
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpPut
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpTrace
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.entity.ByteArrayEntity
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.HttpClient
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.HttpClient
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.HttpClient
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzw: can't find referenced class org.apache.http.client.methods.HttpUriRequest
Warning: com.google.android.gms.internal.zzw$zza: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzw$zza: can't find referenced method 'void setURI(java.net.URI)' in program class com.google.android.gms.internal.zzw$zza
Warning: com.google.android.gms.internal.zzw$zza: can't find referenced class org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Warning: com.google.android.gms.internal.zzx: can't find referenced class org.apache.http.impl.cookie.DateParseException
Warning: com.google.android.gms.internal.zzx: can't find referenced class org.apache.http.impl.cookie.DateUtils
Warning: com.google.android.gms.internal.zzx: can't find referenced class org.apache.http.impl.cookie.DateUtils
Warning: com.google.android.gms.internal.zzy: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzy: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.ProtocolVersion
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.entity.BasicHttpEntity
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicHeader
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicHttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicStatusLine
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.ProtocolVersion
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.entity.BasicHttpEntity
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.entity.BasicHttpEntity
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.entity.BasicHttpEntity
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.entity.BasicHttpEntity
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.entity.BasicHttpEntity
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicHeader
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicHttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicHttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicHttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.message.BasicStatusLine
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.HttpResponse
Warning: com.google.android.gms.internal.zzz: can't find referenced class org.apache.http.HttpEntity
Warning: there were 87 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Exception while processing task
java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:233)
	at proguard.ProGuard.execute(ProGuard.java:98)
	at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
	at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
	at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
	at com.android.builder.tasks.Job.runTask(Job.java:48)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
	at java.lang.Thread.run(Thread.java:745)
:app:dexRelease
```

### PR DESCRIPTION
**Pull request by antoinerousseau**
fixes #48.

### CODE REVIEW

**Comment by peterpme** [comment]
:wave: great job! Any chance we can merge this @evollu ?

**Comment by evollu** [comment]
looks like the whole file is changed. is it necessary?

**Comment by evollu** [comment]
can you just do the fix in one pull and do the formatting in another? thanks

**Comment by antoinerousseau** [comment]
you don't like the formatting improvements?

**Comment by evollu** [comment]
we changed from what you are doing to what we have today so there are some personal preferences involved. We can take time and discuss it.  Lets fix the proguard issue first and quickly.

**Comment by evollu** [comment]
what is the cause for proguard failing?

**Comment by peterpme** [comment]
The only code-related difference in this PR is `componentWillMount` vs `componentDidMount`.

Besides that, it's only helping separate the differences between react native versions.

Can you please expand on what personal preferences are involved?

**Comment by antoinerousseau** [comment]
I feed like it would be quicker for me to discuss the personal preferences now instead of spending time on splitting this commit... and I'm the reporter of the ProGuard issue so I don't think it's urgent is it?

The cause is seen in #49: proguard shouldn't shrink the `com.google.android.gms.*` class names

**Comment by antoinerousseau** [comment]
You can read the result of the change [here](https://github.com/antoinerousseau/react-native-fcm/blob/master/README.md)

**Comment by peterpme** [comment]
I'm still confused, all you did was add instructions and fix grammar. What are the personal preferences?

**Comment by evollu** [comment]
I'm reviewing the pull. I just don't like doing 2 things together in 1 pull.

**Comment by evollu** [comment]
is there specific reason for Changing ComponentWillMount to ComponentDidMount? Is it breaking? just curious

**Comment by antoinerousseau** [comment]
It's usually good practice to do requests in didMount instead of willMount

**Comment by antoinerousseau** [comment]
just added formatting of json blocks

**Comment by antoinerousseau** [comment]
if you don't like my modifications it's fine, I just wanted to help :)

thanks for the project by the way!

**Comment by evollu** [comment]
I'm taking your pull. It looks good. just want to make things clear before i merge before I merge

**Comment by antoinerousseau** [comment]
fair enough! no worries :)

**Comment by evollu** [comment]
is `react-native install` a valid command?

**Comment by antoinerousseau** [comment]
yep they are including rnpm and its "install" command since 0.29

**Comment by antoinerousseau** [comment]
so that people don't need to install rnpm anymore

**Comment by peterpme** [comment]
I would also explicitly add `rnpm link react-native-fcm` and `react-native install react-native-fcm` because `rnpm link` will globally link all of your packages, which could be an issue with older packages or ones that don't necessarily follow the rnpm path.

**Comment by evollu** [comment]
@peterpme agreed. That is the preference I was talking about. I will merge after the change.

regarding the component lifecycle, I don't think we need to wait for component to be mounted/rendered before registering for notification listeners. And `componentWillMount` is the earlier one. thoughts?

**Comment by antoinerousseau** [comment]
From the [doc](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount):
> ### Mounting: componentDidMount
> Invoked once, only on the client (not on the server)
> [...]
> If you want to integrate with other JavaScript frameworks, set timers using setTimeout or setInterval, or send AJAX requests, perform those operations in this method.

**Comment by peterpme** [comment]
@evollu just a heads up, you have it the same way as he does 😄 

Since we're improving the README and I'm going through it myself:

FCM says to put 'com.google.gms.google-services' at the bottom of the file:

`apply plugin: 'com.google.gms.google-services'`

image

**Comment by peterpme** [comment]
Also,

with the supplied instructions, I'm getting a failed build

```
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/peter/Sites/eat-purely/react-native-driver-app/EPDriverApp/android/app/build.gradle' line: 132

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-fcm' could not be found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by evollu** [comment]
@antoinerousseau ok I'm convinced. Lets do it in didmount
@peterpme I've having the same issue. that is why I keep it at the top of the file.

**Comment by peterpme** [comment]
@evollu gotcha! Do you have to add anything to settings.gradle?

**Comment by antoinerousseau** [comment]
@peterpme I also saw that alert about putting `apply plugin` at the end of the file, but when I moved it the alert was still present :/
So I though I'd leave all the `apply plugin` in the same place but I don't know if it changes anything ^^

**Comment by evollu** [comment]
@peterpme nope

**Comment by antoinerousseau** [comment]
@peterpme normally, the `link` command should add these to it:
```gradle
include ':react-native-fcm'
project(':react-native-fcm').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fcm/android')
```

**Comment by peterpme** [comment]
@antoinerousseau I figured! Thanks for clarifying :)

Perhaps we should add that to the README.md as well if folks get that issue?

Also,

I placed my `google-services.json` file under `android/google-services.json` (gcm) but it now belongs under `android/app/google-services.json`

**Comment by evollu** [comment]
@peterpme if user follows instruction correctly, they shouldn't have this issue. The readme is correct on the file placement so we should be good.

**Comment by antoinerousseau** [comment]
well I mean, they should just type the `link` command no? otherwise we add a whole "link manually" section? :/

and for the json the readme says" get `google-services.json` file and place it in `android/app`..." ;)

**Comment by evollu** [comment]
GTG. Have a good night. I will merge tomorrow morning

**Comment by antoinerousseau** [comment]
fyi: https://github.com/facebook/react-native/releases/tag/v0.29.2 :)

**Comment by evollu** [comment]
👍

**Pull request merged**
