### PR TITLE
Remove visual errors for Example

### PR DESCRIPTION
**Pull request by Ajith-Pandian**
Replaced single quotes with double quotes.

### CODE REVIEW

**Comment by evollu** [comment]
eh... any benefits?

**Comment by Ajith-Pandian** [comment]
While seeing react-native-fcm/Examples/simple-fcm-client/app/App.js on browser it has some red marks because of single quotes. Just I would like to remove that to give better readability on browser. NO OTHER BENEFITS.

**Comment by evollu** [comment]
what browser are you using? My chrome works just fine. I use single quotes everywhere and never got the issue

**Comment by Ajith-Pandian** [comment]
Even I'm using Chrome.
screen shot 2017-11-30 at 1 22 09 pm

I mean this one as "visual error". If it is misleading title & unwanted PR please ignore.

**Comment by evollu** [comment]
i see. How about just change line 158?

**Comment by Ajith-Pandian** [comment]
I thought it would be better to remove all single quotes. Some styles also has single quotes. It may give that red mark. I'm not sure about that.

**Comment by evollu** [comment]
try it and see.
It is just chrome change parse jsx. single quotes in standard js should be fine

**Comment by Ajith-Pandian** [comment]
I think this PR is useless. Closing it.

**Pull request closed without merging**
