### PR TITLE
added registerForRemoteNotifications fixes #44

### LINKED ISSUE #44: registerForRemoteNotifications
Hi,

I'm struggling to get the remote push notifications working on IOS.
Reading through the documentation I found that registerForRemoteNotifications should be called to allow remote push notifications to be received. However in the code I only see registerUserNotificationSettings being called.
I also read that on macOS you only need to call that method and it will call the registerForRemoteNotifications for you, however on iOS it seems you'd have to explicitly call that method for remote push notifications to work.

Am I missing something in the documentation or should this method be called?

### PR DESCRIPTION
**Pull request by benoist**
This fixes the issue from #44

### CODE REVIEW

**Comment by evollu** [comment]
can you do me a favor and port the whole registration code from fcm into the library?
https://github.com/firebase/quickstart-ios/blob/master/messaging/FCM/AppDelegate.m#L36-L41

**Comment by benoist** [comment]
Yep will do

**Comment by benoist** [comment]
Actually looking at it, it's exactly the same now, apart from that there is a split on the app variable to check if it's iOS 8+

**Comment by evollu** [comment]
great merging

**Pull request merged**
