### PR TITLE
IOS: Added identification for which action was taken in case there wa…

### PR DESCRIPTION
**Pull request by alialamine**
Added the action_identifier key when the action has been taken

### CODE REVIEW

**Comment by evollu** [comment]
can you provide more detail about the issue?

**Comment by alialamine** [comment]
In my application, I have two buttons on the notification: View and Delete

With the current behaviour, there is no way to detect which button is pressed, so this pull request adds the actionIdentifier to be returned with the results to be able to detect which button is pressed.

**Comment by evollu** [comment]
can you share more about how you did it?
I wonder your can solve the problem for #325

**Comment by sibelius** [comment]
I think it is worth to add this to the example

**Comment by evollu** [comment]
looks good. can you use `_actionIdentifier` for the flag name?
@sibelius what do you think about flag naming convention?

**Comment by sibelius** [comment]
`_actionIdentifier` is a good name

**Comment by evollu** [comment]
published in v6.1.0

**Pull request merged**
