### PR TITLE
Add deleteEntityToken and getEntityToken methods

### PR DESCRIPTION
**Pull request by ditkachuk**
Added missing method for android implementation of android `InstanceId` class.
https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID

### CODE REVIEW

**Comment by evollu** [comment]
how is `getEntityFCMToken` different from `getFCMToken`?

**Comment by ditkachuk** [comment]
We have a problem that `getFCMToken` doesn't create new token after deleting.

Soon we add same methods in ios part. Will check about that

**Comment by megazoll** [comment]
@evollu correct link to the docs is https://developers.google.com/android/reference/com/google/firebase/iid/FirebaseInstanceId

There two methods for getting token, and delete token working only with scoped token.

**Comment by ditkachuk** [comment]
ios docs: https://firebase.google.com/docs/reference/ios/firebaseinstanceid/api/reference/Classes/FIRInstanceID#/c:objc(cs)FIRInstanceID(im)tokenWithAuthorizedEntity:scope:options:handler:

**Comment by ditkachuk** [comment]
Is use this methods for token generation it can fix #776 this kinds of troubles

**Comment by evollu** [comment]
can you rename `deleteFCMToken` to `deleteEntityFCMToken` so it matches the get function?

**Pull request merged**
