### PR TITLE
Add .unsubscribe() method to FCM.on()

### PR DESCRIPTION
**Pull request by ethan37**
https://github.com/evollu/react-native-fcm/issues/260

:)

Edit. sorry for the useless changes in the PR, don't mind them!

### CODE REVIEW

**Comment by evollu** [comment]
why don't we just return what DeviceEventEmitter returns and people just call .remove(). so that it will be inline with other facebook apis

**Comment by ethan37** [comment]
Do you mean

```javascript
FCM.on = (event, callback) => {
    const nativeEvent = eventsMap[event];
    if (!nativeEvent) {
        throw new Error('FCM event must be "refreshToken" or "notification"');
    }
    return DeviceEventEmitter.addListener(nativeEvent, callback);
};
```

?

**Comment by evollu** [comment]
yes

**Comment by ethan37** [comment]
@evollu https://github.com/evollu/react-native-fcm/pull/263

**Pull request closed without merging**
