### PR TITLE
add channel

### PR DESCRIPTION
**Pull request by evollu**
the app crashes because of 
`compile "com.android.support:support-core-utils:26.1.0"`

### CODE REVIEW

**Comment by Titozzz** [comment]
By the way i tested this on Android 8 and Android 7.1, and local notification are working <3

**Comment by evollu** [comment]
@Titozzz you can target this branch in your npm.
yarn add react-native-fcm@git://github.com/evollu/react-native-fcm#sdk-26

**Comment by evollu** [comment]
There are 2 reasons why the PR is not merged.
1. as I mentioned in #698, I can't get my sample project to compile.
2. facebook hasn't officially support compiling with SDK 26. merging this into main branch will force everyone to upgrade to an non-officially supported state.

**Comment by sahil290791** [comment]
I am still not getting any notification icon when the app is in background, but the app is getting the data in registerKilledListeners as per the example. Any idea how can I get the icon in the notification shade? I am using sdk-26 branch of `react-native-fcm`.

```
compileSdkVersion 26
buildToolsVersion '26.0.2'
targetSdkVersion 26
```

**Comment by sahil290791** [comment]
@evollu I have created a notification channel by referring this: https://github.com/invertase/react-native-firebase-docs/blob/master/docs/notifications/android-channels.md

Now I can see the channel listed in `settings > apps > my-app > notifications`. But still I am unable to see the notification icon in the notification tray/shade.

**Comment by sahil290791** [comment]
@evollu its finally working, needed to send `channel` key inside `custom_notification`:
```
"data" : {
 	"show_in_foreground": true,
 	"content_available" : true,
 	"priority" : "high",
	 "title" : "Sample title",
	 "message": "Sample message",
	 "type": "DEEPLINK",
	 "sound": "default",
	 "vibrate": 300,
         "lights":  true,
          "utm_medium": "medium",
	  "utm_campaign": "campaign",
	  "utm_content": "content",
	  "utm_term": "term",
	  "utm_source": "example",
	  "channel": "default",
	 "custom_notification" : {
	   "body" : "Sample body",
	   "color": "#F58024",
	   "title" : "Sample title",
	   "type": "DEEPLINK",
            "sound": "default",
	   "icon": "ic_notif",
	   "channel": "default",
	   "picture": "image_url"
	 },
 },
```

Added channel creation in registerListeners:
```js
export function registerAppListener(openPushNotification, handleOpenURL) {
  const channel = new firebase.notifications.Android.Channel('default',
  'Notification', firebase.notifications.Android.Importance.Max)
  .setDescription('Receive notifications');

  // channel id is set as: default
  // Create the channel
  firebase.notifications().android.createChannel(channel);
}
```

The channel id in the notification payload should match the one given while channel creation.

**Comment by cylim** [comment]
@sahil290791 

According to the example of the changes, your registerAppListener can be replaced with
```js
FCM.createNotificationChannel({
      id: 'default',
      name: 'Default',
      description: 'general usage',
      priority: 'high'
})
```

**Pull request merged**
