### PR TITLE
Fix cocoapods react-native-fcm 11

### PR DESCRIPTION
**Pull request by Titozzz**
This Requires cocoapods 1.4 to run
sudo gem install cocoapods --pre

### CODE REVIEW

**Comment by evollu** [comment]
`s.dependency "React"` does that mean I need to have React and pod library as well?

**Comment by Titozzz** [comment]
Yeah I'm setting up a project with exactly 0 'libraries' and everything is in my podfile
It looks like that

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'lol' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
  pod 'react-native-google-signin', :path => '../node_modules/react-native-google-signin'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-navigation', :path => '../node_modules/react-native-navigation'
  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

end

```

**Comment by Titozzz** [comment]
I've decided to give a try to the new syntax, which hopefully will give me more solid iOS builds

**Comment by evollu** [comment]
but the facebook's starter project has react as library dependency in main project. Won't this cause React getting compiled twice?

**Comment by Titozzz** [comment]
Well, yes, I had to start from scratch to create a project with no dependency on react and follow this tutorial partially https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

The thing is, now if you use react-native link, and you have a podfile in your ios project, they consider you did the same and it will only link the repo podspec to the project. If you don't use cocoapods, then react-native link will behave as before. By making this change, they made hybrid projects (with react in libraries and manual pods) really hard to maintain, that's why I moved my codebase to the new syntax, and I think libraries will have to update.. :/

One of the advantage I have is parallelization is working flawlessly now and I haven't got any build issues since I made my changes

**Comment by evollu** [comment]
@Titozzz yes can do another PR for documentation?

**Comment by Titozzz** [comment]
Will do

**Pull request merged**
