### PR TITLE
added big picture style to android notification

### PR DESCRIPTION
**Pull request by XeniousSoftware**
by just adding a key called picture to  the notification payload, we can
display image on android notification.

### CODE REVIEW

**Comment by evollu** [comment]
great can you add some documentation in readme? or add some code in example project?

**Comment by christianchown** [comment]
@XeniousSoftware also, picture will need to be added to LocalNotification interface in index.d.ts

**Comment by evollu** [comment]
@XeniousSoftware hi haven't heard from you for a while. are you working on it?
I can continue the work if you are busy

**Comment by XeniousSoftware** [comment]
oh sorry, yes i was little bit busy :(
yes please you can continue the work.

**Comment by khalid283** [comment]
@evollu Image does not work even after including the picture url

```javascript 
sendRemote(notif) {
   console.log('send');
    FCM.presentLocalNotification({
      title: notif.title,
      body: notif.body,
      sound: "default",
      priority: "high",
      large_icon: "ic_launcher",  
      icon: "ic_launcher",
      big_text: notif.title,
      sub_text: notif.body,
      color: "red",
      picture: 'https://pbs.twimg.com/profile_images/733010550670557184/aMmM_m3g.jpg',
      vibrate: 300,
      wake_screen: true,
      click_action: notif.click_action,
      show_in_foreground: true,
      local: true
    });
  }
```
Any suggestion please.

**Pull request merged**
