### PR TITLE
Revert "Upgrade Android build tools to 25.0.1"

### PR DESCRIPTION
**Pull request by evollu**
Reverts evollu/react-native-fcm#342

### CODE REVIEW

**Comment by sibelius** [comment]
why?

**Comment by evollu** [comment]
put this in branch build-25 and released as 6.1.1-build-25

**Comment by sibelius** [comment]
react-native-maps upgraded to build 25 as well

**Comment by evollu** [comment]
hmm seems I was wrong. updating build number don't impact anything here. I will update build number in master

**Pull request merged**
