### PR TITLE
fix fail notification schedule after reboot on Android

### PR DESCRIPTION
**Pull request by germanst**

### CODE REVIEW

**Comment by evollu** [comment]
released in v11.2.0

**Comment by douglasjunior** [comment]
This PR is giving error at [this line](https://github.com/evollu/react-native-fcm/blob/58ed2d29c81de6d9be6f1c5a74d43f58a89f7896/android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java#L61).

```
W/Bundle: Attempt to cast generated internal exception:
          java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
              at android.os.BaseBundle.getLong(BaseBundle.java:835)
              at android.os.BaseBundle.getLong(BaseBundle.java:817)
              at com.evollu.react.fcm.FIRLocalMessagingHelper.sendNotificationScheduled(FIRLocalMessagingHelper.java:61)
              at com.evollu.react.fcm.FIRMessagingModule.scheduleLocalNotification(FIRMessagingModule.java:109)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
              at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
              at android.os.Handler.handleCallback(Handler.java:746)
              at android.os.Handler.dispatchMessage(Handler.java:95)
              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
              at android.os.Looper.loop(Looper.java:148)
              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
              at java.lang.Thread.run(Thread.java:818)
```

Before this PR I had no problems.

**Comment by douglasjunior** [comment]
To make sure that the problema is not in my code, I wrapped my value with `parseInt`, but no worked.

```js
        const notification = {
            fire_date: parseInt(fireDate),       
            ...
        }
        FCM.scheduleLocalNotification(notification);
```

**Comment by evollu** [comment]
try directly `fire_date: 1516484334`? `getLong` won't get called if `getDouble` succeeds

**Comment by douglasjunior** [comment]
> getLong won't get called if getDouble succeeds

This is not true.

In java, this code runs like this:

```java
Long longValue = bundle.getLong("fire_date");
Double doubleValue = bundle.getDouble("fire_date", longValue);
Long fireDate = Math.round(doubleValue);
```

**Comment by evollu** [comment]
@douglasjunior my bad, confused with `a || b`
fixed in master with following code
```
long fireDate = Math.round(bundle.getDouble("fire_date"));
        if(fireDate == 0){
            fireDate = Math.round(bundle.getLong("fire_date"));
        }
        if (fireDate == 0) {
            Log.e(TAG, "failed to schedule notification because fire date is missing");
            return;
        }
```

**Comment by douglasjunior** [comment]
Thanks!

**Pull request merged**
