### PR TITLE
Firestack compatibility

### PR DESCRIPTION
**Pull request by slycoder**
In case someone also decides to use firestack (https://github.com/fullstackreact/react-native-firestack), that comes prepackaged with most of the Firebase libraries.  This PR just adds the Firestack directories to the search paths so that if they have this set up it'll pick up the frameworks from there.  It shouldn't affect things if you still want to install the frameworks via cocoapods as those paths are still there.

### CODE REVIEW

**Comment by evollu** [comment]
thanks for your pull. I see you changed importing from .h file to importing module. Firestack doesn't include header file in its code (even Pods version of firebase has it)?
I tested your pull version and `@import Firebase;` failed for me.
can you try if this works?
```
@import FirebaseInstanceID;
@import FirebaseMessaging;
```

**Comment by slycoder** [comment]
Hey sorry about that and thanks for checking!  I realized that in my test project I had accidentally dragged and dropped a few dependencies (ugh, xcode!).  I'll work on making sure that this works both in firestack and with cocoapods and update the PR in the nest few days.

**Comment by evollu** [comment]
I think your pull is failing only when user import .framework file into project manually without cocoapods (which is what I'm doing now)

**Comment by jeromegrosse** [comment]
@evollu You mentioned that it failed when not using Cocoapods. Is it working now?

**Comment by antoinerousseau** [comment]
I see that @evollu pushed https://github.com/evollu/react-native-fcm/commit/e03ef47e37f022e94bf4d703a7a97ae2a006526b to 2.1.0

**Pull request merged**
