### PR TITLE
upgrade versions of android target, compile sdk and support-core-utils

### PR DESCRIPTION
**Pull request by valerit**

### CODE REVIEW

**Comment by evollu** [comment]
is there a particular reason to upgrade?

**Comment by valerit** [comment]
https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by valerit** [comment]
`Google Play will require that new apps target at least Android 8.0 (API level 26) from August 1, 2018, and that app updates target Android 8.0 from November 1, 2018.`

**Comment by evollu** [comment]
we are on 26. but I guess it doesn't hurt to upgrade

**Pull request merged**
