### PR TITLE
Fix FCMEvent.Notification callback argument

### PR DESCRIPTION
**Pull request by mahm**
I set the callback argument because Notification returns undefined.

### CODE REVIEW

**Comment by Kaishley** [comment]
@evollu Please merge and release this :)

**Comment by chrusart** [comment]
From docs:
// there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload

It works (no exception) for me with callback(data) (all values are there) but not sure it should be data object there.

Custom data (key-value) are directly in data object, other notification values like message text and title are in data.fcm object. It is not correct according to docs. Proper object should be created from data prabably, or docs changed.

I just started using fcm today and new in RN, so be forgiving :)

Tested using 'Notifications' in Firebase developer console.
Android Emulator, RN 0.40.0, react-native-fcm@6.0.1

**Comment by evollu** [comment]
buglished

**Comment by chrusart** [comment]
Ok, it just depends how we create the object on server side i guess.

**Pull request merged**
