### PR TITLE
update FAQ for iOS background question

### PR DESCRIPTION
**Pull request by element6**
Hi,

Thanks for your work!

I thought I'll add another FAQ, because I ran into this issue and hopefully it will save time for others.

Cheers,
Gary

### CODE REVIEW

**Comment by evollu** [comment]
@element6 thanks for you pull. You can also add the flags through xcode UI. I will merge and update readme after I merge the other pull

**Comment by evollu** [comment]
can you resolve the conflicts? or do you want to me apply the changes for you?

**Comment by evollu** [comment]
readme updated

**Comment by element6** [comment]
Thanks for the update, the UI method is good

**Pull request closed without merging**
